replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/demand-forecast-service
  tag: "2d144b72013ec88766b6b1f1f685577b1c6185ca"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
