apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demand-forecast-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SaiMudunuri04/demand-forecast-service.git
    targetRevision: main
    path: k8s/helm/demand-forecast-service
  destination:
    server: https://kubernetes.default.svc
    namespace: demand-forecast-service
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
